# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: php:7.1
      - image: selenium/standalone-chrome:3
    working_directory: ~/otb-test
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/bin --filename=composer
            php -r "unlink('composer-setup.php');"

      # Update Composer and install dependencies
      - run: composer self-update
      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: mkdir ./behat_screenshots
      # add an empty file so that the directory isn't empty (else copy may fail)
      - run: touch var/behat_screenshots/empty.txt

      - run:
          name: Run Behat tests
          command: php bin/behat
          # Export environment variable for this single command shell
          environment:
            BEHAT_SCREENSHOTS: '1'

      - store_artifacts:
          path: ./behat_screenshots/
