# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: php:7
      - image: selenium/standalone-chrome:3
    working_directory: ~/otb-test
    steps:
      - checkout

      # Update Composer and install dependencies
      - run: composer self-update
      - run: composer install --prefer-dist

      - run: mkdir var/behat_screenshots/
      # add an empty file so that the directory isn't empty (else copy may fail)
      - run: touch var/behat_screenshots/empty.txt

      - run:
        name: Run Behat tests
        command: php bin/behat
        # Export environment variable for this single command shell
        environment:
          BEHAT_SCREENSHOTS: '1'

      - store_artifacts:
        path: var/behat_screenshots/
